from setuptools import setup, find_packages

extras_require = {}

setup(
    name='bspider',
    version=open('./bspider/VERSION').read().strip(),
    description='A high-level distributed crawling framework Git: https://github.com/littlebai3618/bspider',
    author='baii',
    author_email='2624386844@qq.com',
    license='BSD',
    packages=find_packages(exclude=('tests', 'tests.*')),
    include_package_data=True,
    zip_safe=False,
    entry_points={
        'console_scripts': ['bspider = bspider.cmdline:execute']
    },
    classifiers=[
        'Framework :: Scrapy',
        'Development Status :: 5 - Production/Stable',
        'Environment :: Console',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: BSD License',
        'Operating System :: OS Independent',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: Implementation :: CPython',
        'Topic :: Internet :: WWW/HTTP',
        'Topic :: Software Development :: Libraries :: Application Frameworks',
        'Topic :: Software Development :: Libraries :: Python Modules',
    ],
    python_requires='>=3.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*',
    install_requires=[
        "aiohttp==3.7.4.post0",
        "aiomysql==0.0.21",
        "aiormq==2.7.2",
        "aniso8601==9.0.1",
        "APScheduler==3.7.0",
        "asn1crypto==1.4.0",
        "async-timeout==3.0.1",
        "attrs==21.2.0",
        "casbin==1.0.4",
        "certifi==2020.12.5",
        "cffi==1.14.5",
        "chardet==4.0.0",
        "click==8.0.0",
        "cryptography==3.3.2",
        "DBUtils==2.0.1",
        "Flask==2.0.0",
        "Flask-Cors==3.0.10",
        "Flask-HTTPAuth==4.3.0",
        "Flask-WTF==0.14.3",
        "gevent==21.1.2",
        "greenlet==1.1.0",
        "gunicorn==20.1.0",
        "idna==3.1",
        "itsdangerous==2.0.0",
        "Jinja2==3.0.0",
        "lxml==4.6.3",
        "MarkupSafe==2.0.0",
        "meld3==2.0.1",
        "multidict==5.1.0",
        "pamqp==3.0.1",
        "pika==1.2.0",
        "psutil==5.8.0",
        "pycparser==2.20",
        "PyMySQL==0.9.3",
        "pytz==2021.1",
        "PyYAML==5.4.1",
        "redis==3.5.3",
        "requests==2.25.1",
        "simpleeval==0.9.10",
        "six==1.16.0",
        "supervisor==4.2.2",
        "typing-extensions==3.10.0.0",
        "tzlocal==2.1",
        "urllib3==1.26.4",
        "voluptuous==0.12.1",
        "Werkzeug==2.0.0",
        "WTForms==2.3.3",
        "xpinyin==0.7.6",
        "yarl==1.3.0",
        "zope.event==4.5.0",
        "zope.interface==5.4.0"
    ],
    extras_require=extras_require,
)
